<?php

/*
 * Fixed texts of the public site, in English. It must have exactly the same keys as it.php
 * (a test checks this). No business data is invented: where information is missing, the text says so.
 * Placeholders in braces ({n}, {name}, ...) are replaced by t(). Draft wording: the owner may correct it.
 */

return [
    // Navigation and structure
    'a11y.skip' => 'Skip to content',
    'nav.label' => 'Main navigation',
    'nav.home' => 'Home',
    'nav.farm' => 'The farm',
    'nav.apartments' => 'Apartments',
    'nav.around' => 'Around us',
    'nav.contact' => 'Contact',
    'nav.request' => 'Request availability',
    'nav.switch' => 'Italiano',
    'nav.privacy' => 'Privacy',
    'nav.cookies' => 'Cookies',
    'nav.breadcrumb' => 'Breadcrumb',
    'footer.contacts' => 'Contact',
    'error.home' => 'Back to the home page',

    // Home
    'home.description' => 'Agriturismo La Volta: apartments for your stay. Request availability online.',
    'home.lead' => 'Apartments for your stay at our agriturismo.',
    'home.see_apartments' => 'See the apartments',
    'home.more' => 'Find out more',

    // Information pages
    'page.pending' => 'The text of this page will be added by the owner.',
    'farm.title' => 'The farm',
    'farm.description' => 'The agriturismo La Volta.',
    'around.title' => 'Around us',
    'around.description' => 'What to see around the agriturismo La Volta.',

    // Apartments
    'apartments.title' => 'Apartments',
    'apartments.description' => 'The apartments of the agriturismo La Volta.',
    'apartments.none' => 'The apartments will soon be listed on this page.',
    'apartments.discover' => 'Discover the {name} apartment',
    'apartment.description' => 'Description',
    'apartment.times' => 'Times',
    'apartment.amenities' => 'Amenities',
    'apartment.rules' => 'House rules',
    'apartment.cta_title' => 'Interested in this apartment?',
    'apartment.no_online' => 'Requests for this apartment cannot be sent online: please contact us directly.',
    'apartment.check_in_between' => 'Arrival from {from} to {to}',
    'apartment.check_in_from' => 'Arrival from {from}',
    'apartment.check_out_until' => 'Departure by {to}',
    'fact.guests' => 'Up to {n} guests',
    'fact.bedroom' => '{n} bedroom',
    'fact.bedrooms' => '{n} bedrooms',
    'fact.bed' => '{n} bed',
    'fact.beds' => '{n} beds',
    'fact.price_from' => 'From {price} per night (indicative price)',
    'photo.placeholder' => 'Photograph coming soon',
    'photo.alt' => 'Photograph of {name}: placeholder, the photograph will be added soon',

    // Contact
    'contact.title' => 'Contact',
    'contact.description' => 'How to contact the agriturismo La Volta.',
    'contact.pending' => 'Our contact details will be published soon. In the meantime you can send us an availability request.',
    'contact.phone' => 'Phone',
    'contact.email' => 'Email',
    'contact.address' => 'Address',
    'contact.map' => 'Open the location on Google Maps',
    'contact.whatsapp_cta' => 'Write to us on WhatsApp',
    'contact.whatsapp_hint' => '(the message is pre-filled and you can edit it before sending)',

    // Legal texts (drafts)
    'legal.draft' => 'Draft: this text must be checked and completed by the owner or an advisor before publication.',
    'privacy.title' => 'Privacy notice',
    'privacy.description' => 'How we handle the data sent with the availability request.',
    'privacy.data.h' => 'What data we collect',
    'privacy.data.p' => 'With the availability request we collect your first name, last name, email address, phone number, any notes, the dates and the number of guests and pets, and the date on which you accepted this notice. We do not ask for or collect payment data.',
    'privacy.purpose.h' => 'Why we use it',
    'privacy.purpose.p' => 'We use the data only to answer your request and, if the request is confirmed, to manage your stay.',
    'privacy.security.h' => 'Technical measures',
    'privacy.security.p' => 'To limit abuse of the form we keep, for a short time, a non-reversible fingerprint of the network address of the device. The public site uses no cookies and no tracking tools.',
    'privacy.todo.h' => 'To be completed by the owner',
    'privacy.todo.controller' => 'Data controller and contact details: [to be completed]',
    'privacy.todo.basis' => 'Legal basis for the processing: [to be completed]',
    'privacy.todo.retention' => 'Data retention periods: [to be completed]',
    'privacy.todo.recipients' => 'Recipients and providers (hosting, email): [to be completed]',
    'privacy.todo.rights' => 'Rights of the data subject and how to exercise them: [to be completed]',
    'cookies.title' => 'Cookies',
    'cookies.description' => 'The cookies used by the site.',
    'cookies.public.h' => 'Public site',
    'cookies.public.p' => 'The public pages and the request form set no cookies and use no tracking or marketing tools.',
    'cookies.admin.h' => 'Private area',
    'cookies.admin.p' => 'The private area for the manager uses a single technical session cookie, needed to sign in. It does not concern visitors of the site.',
    'cookies.future.h' => 'Updates',
    'cookies.future.p' => 'If analytics tools or other non-technical cookies are introduced in the future, this page will be updated and, where required, consent will be asked for.',

    // Availability request
    'request.title' => 'Request availability',
    'request.description' => 'Ask for the availability of an apartment: choose your dates and guests.',
    'request.intro' => 'Enter your dates and guests: we will show you the available apartments and the price. Sending the request is not a booking.',
    'flow.step.label' => 'Request steps',
    'flow.step.1' => 'Dates and guests',
    'flow.step.2' => 'Apartment',
    'flow.step.3' => 'Your details',
    'flow.step.4' => 'Summary and send',
    'flow.errors_intro' => 'Please check these fields:',
    'flow.apartments.title' => 'Available apartments',
    'flow.apartments.none' => 'There are no apartments available for these dates and guests. Try other dates or contact us.',
    'flow.stay_line' => 'From {in} to {out} ({nights}) · {guests}.',
    'flow.price_total' => 'Total',
    'flow.whatsapp' => 'Prefer to write to us? Ask on WhatsApp',
    'flow.price_note' => 'The price is calculated by the system and is indicative until the request is confirmed by the manager.',
    'flow.details.title' => 'Your details',
    'flow.summary.title' => 'Summary and send',
    'flow.not_a_booking' => 'This is an availability request, not a booking: the stay is confirmed only after the manager replies.',
    'flow.received.title' => 'Request received',
    'flow.received.lead' => 'We have received your availability request.',
    'flow.received.reference' => 'Request reference',
    'flow.received.next' => 'We will reply as soon as possible to the email address you gave us.',
    'flow.error.title' => 'The request could not be sent',
    'flow.error.too_many' => 'You have sent too many requests in a short time. Please try again later or contact us.',
    'flow.error.conflict' => 'In the meantime these dates are no longer available for the chosen apartment. Please try other dates.',
    'flow.error.busy' => 'The system is busy: please try again in a moment.',
    'flow.error.unavailable' => 'The chosen apartment cannot take this request online. Please contact us directly.',
    'flow.error.expired' => 'The form has expired: please check your details and send it again.',
    'flow.error.too_fast' => 'The form was sent too quickly: please check your details and try again.',
    'summary.apartment' => 'Apartment',
    'summary.dates' => 'Dates',
    'summary.contact' => 'Contact',
    'summary.price' => 'Price',
    'summary.total' => 'Total',
    'summary.unquoted' => 'the manager will tell you the price in the reply.',

    // Form fields and buttons
    'form.check_in' => 'Arrival',
    'form.check_out' => 'Departure',
    'form.guests' => 'Guests',
    'form.adults' => 'Adults',
    'form.children' => 'Children',
    'form.pets' => 'Pets',
    'form.first_name' => 'First name',
    'form.last_name' => 'Last name',
    'form.email' => 'Email',
    'form.phone' => 'Phone',
    'form.notes' => 'Notes (optional)',
    'form.required_all' => 'All fields are required.',
    'form.required_except_notes' => 'All fields are required, except the notes.',
    'form.honeypot' => 'Leave this field empty',
    'form.privacy_before' => 'I have read the',
    'form.privacy_link' => 'privacy notice',
    'form.privacy_after' => 'and I consent to the processing of my data in order to answer the request.',
    'form.search' => 'Search apartments',
    'form.choose' => 'Choose {name}',
    'form.continue' => 'Continue',
    'form.send' => 'Send the request',
    'form.back' => 'Back',
    'form.change_search' => 'Change dates or guests',
    'form.edit_data' => 'Edit my details',

    // Units
    'unit.night' => '{n} night',
    'unit.nights' => '{n} nights',
    'unit.adult' => '{n} adult',
    'unit.adults' => '{n} adults',
    'unit.child' => '{n} child',
    'unit.children' => '{n} children',
    'unit.pet' => '{n} pet',
    'unit.pets' => '{n} pets',

    // Validation errors
    'err.generic' => 'Please check this field.',
    'err.invalid_date' => 'Enter a valid date.',
    'err.check_out_not_after_check_in' => 'The departure must be after the arrival.',
    'err.stay_too_long' => 'The stay is too long for an online request: please contact us.',
    'err.check_in_in_past' => 'The arrival date cannot be in the past.',
    'err.check_in_too_far' => 'The arrival date is too far ahead.',
    'err.invalid_adults' => 'Enter at least one adult.',
    'err.invalid_children' => 'Enter a valid number of children.',
    'err.invalid_pets' => 'Enter a valid number of pets.',
    'err.invalid_first_name' => 'Enter your first name.',
    'err.invalid_last_name' => 'Enter your last name.',
    'err.invalid_email' => 'Enter a valid email address.',
    'err.invalid_phone' => 'Enter a valid phone number.',
    'err.notes_too_long' => 'The notes are too long.',
    'err.invalid_locale' => 'Invalid language.',
    'err.privacy_required' => 'To send the request you must accept the privacy notice.',
    'err.invalid_apartment' => 'Choose an apartment.',
    'err.over_capacity' => 'The number of guests exceeds the capacity of the apartment.',
    'err.too_many_children' => 'For this apartment the children can be at most {max}.',
    'err.pets_not_allowed' => 'Pets are not allowed in this apartment.',
    'err.too_many_pets' => 'For this apartment the pets can be at most {max}.',
    'err.below_minimum_stay' => 'For these dates the minimum stay is {min} nights.',
];
