<?php

/*
 * Testi fissi del sito pubblico, in italiano. Il file in inglese (en.php) deve avere le stesse chiavi:
 * un test lo verifica. Nessun dato di business inventato: dove manca l’informazione il testo lo dice.
 * I segnaposto tra graffe ({n}, {name}, ...) vengono sostituiti da t().
 */

return [
    // Navigazione e struttura
    'a11y.skip' => 'Salta al contenuto',
    'nav.label' => 'Navigazione principale',
    'nav.home' => 'Home',
    'nav.farm' => 'L’agriturismo',
    'nav.apartments' => 'Appartamenti',
    'nav.around' => 'Dintorni',
    'nav.contact' => 'Contatti',
    'nav.request' => 'Richiedi disponibilità',
    'nav.switch' => 'English',
    'nav.privacy' => 'Privacy',
    'nav.cookies' => 'Cookie',
    'nav.breadcrumb' => 'Percorso',
    'footer.contacts' => 'Contatti',
    'error.home' => 'Torna alla pagina iniziale',

    // Home
    'home.description' => 'Agriturismo La Volta: appartamenti per il tuo soggiorno. Richiedi la disponibilità online.',
    'home.lead' => 'Appartamenti per il vostro soggiorno in agriturismo.',
    'home.see_apartments' => 'Vedi gli appartamenti',
    'home.more' => 'Scopri di più',

    // Pagine informative
    'page.pending' => 'I testi di questa pagina saranno inseriti a cura del titolare.',
    'farm.title' => 'L’agriturismo',
    'farm.description' => 'L’agriturismo La Volta.',
    'around.title' => 'Dintorni',
    'around.description' => 'Cosa vedere nei dintorni dell’agriturismo La Volta.',

    // Appartamenti
    'apartments.title' => 'Appartamenti',
    'apartments.description' => 'Gli appartamenti dell’agriturismo La Volta.',
    'apartments.none' => 'Gli appartamenti saranno presto disponibili in questa pagina.',
    'apartments.discover' => 'Scopri l’appartamento {name}',
    'apartment.description' => 'Descrizione',
    'apartment.times' => 'Orari',
    'apartment.rules' => 'Regole della casa',
    'apartment.cta_title' => 'Ti interessa questo appartamento?',
    'apartment.no_online' => 'Per questo appartamento non è possibile inviare la richiesta online: contattaci direttamente.',
    'apartment.check_in_between' => 'Arrivo dalle {from} alle {to}',
    'apartment.check_in_from' => 'Arrivo dalle {from}',
    'apartment.check_out_until' => 'Partenza entro le {to}',
    'fact.guests' => 'Fino a {n} ospiti',
    'fact.bedroom' => '{n} camera da letto',
    'fact.bedrooms' => '{n} camere da letto',
    'fact.bed' => '{n} posto letto',
    'fact.beds' => '{n} posti letto',
    'fact.price_from' => 'Da {price} a notte (prezzo indicativo)',
    'photo.placeholder' => 'Fotografia in arrivo',
    'photo.alt' => 'Fotografia di {name}: segnaposto, la fotografia sarà inserita a breve',

    // Contatti
    'contact.title' => 'Contatti',
    'contact.description' => 'Come contattare l’agriturismo La Volta.',
    'contact.pending' => 'I recapiti saranno pubblicati a breve. Nel frattempo puoi inviarci una richiesta di disponibilità.',
    'contact.phone' => 'Telefono',
    'contact.email' => 'Email',
    'contact.address' => 'Indirizzo',
    'contact.whatsapp_cta' => 'Scrivici su WhatsApp',
    'contact.whatsapp_hint' => '(il messaggio è precompilato e puoi modificarlo prima di inviarlo)',

    // Testi legali (bozze)
    'legal.draft' => 'Bozza: questo testo deve essere verificato e completato dal titolare o da un consulente prima della pubblicazione.',
    'privacy.title' => 'Informativa sulla privacy',
    'privacy.description' => 'Come trattiamo i dati inviati con la richiesta di disponibilità.',
    'privacy.data.h' => 'Quali dati raccogliamo',
    'privacy.data.p' => 'Con la richiesta di disponibilità raccogliamo nome, cognome, indirizzo email, numero di telefono, le eventuali note, le date e il numero di ospiti e animali, e la data in cui hai accettato questa informativa. Non chiediamo e non raccogliamo dati di pagamento.',
    'privacy.purpose.h' => 'Perché li usiamo',
    'privacy.purpose.p' => 'Usiamo i dati solo per rispondere alla tua richiesta e, se la richiesta viene confermata, per gestire il soggiorno.',
    'privacy.security.h' => 'Misure tecniche',
    'privacy.security.p' => 'Per limitare gli abusi del modulo conserviamo per poco tempo un’impronta non reversibile dell’indirizzo di rete del dispositivo. Il sito pubblico non usa cookie né strumenti di tracciamento.',
    'privacy.todo.h' => 'Da completare a cura del titolare',
    'privacy.todo.controller' => 'Titolare del trattamento e recapiti: [da completare]',
    'privacy.todo.basis' => 'Base giuridica del trattamento: [da completare]',
    'privacy.todo.retention' => 'Tempi di conservazione dei dati: [da completare]',
    'privacy.todo.recipients' => 'Destinatari e fornitori (hosting, posta elettronica): [da completare]',
    'privacy.todo.rights' => 'Diritti dell’interessato e come esercitarli: [da completare]',
    'cookies.title' => 'Cookie',
    'cookies.description' => 'I cookie usati dal sito.',
    'cookies.public.h' => 'Sito pubblico',
    'cookies.public.p' => 'Le pagine pubbliche e il modulo di richiesta non impostano cookie e non usano strumenti di tracciamento o di marketing.',
    'cookies.admin.h' => 'Area riservata',
    'cookies.admin.p' => 'L’area riservata al gestore usa un solo cookie tecnico di sessione, necessario all’accesso. Non riguarda i visitatori del sito.',
    'cookies.future.h' => 'Aggiornamenti',
    'cookies.future.p' => 'Se in futuro verranno introdotti strumenti di analisi o altri cookie non tecnici, questa pagina sarà aggiornata e, dove necessario, verrà richiesto il consenso.',

    // Richiesta di disponibilità
    'request.title' => 'Richiedi disponibilità',
    'request.description' => 'Chiedi la disponibilità di un appartamento: scegli le date e gli ospiti.',
    'request.intro' => 'Indica le date e gli ospiti: ti mostreremo gli appartamenti disponibili e il prezzo. L’invio della richiesta non è una prenotazione.',
    'flow.step.label' => 'Passaggi della richiesta',
    'flow.step.1' => 'Date e ospiti',
    'flow.step.2' => 'Appartamento',
    'flow.step.3' => 'I tuoi dati',
    'flow.step.4' => 'Riepilogo e invio',
    'flow.errors_intro' => 'Controlla questi campi:',
    'flow.apartments.title' => 'Appartamenti disponibili',
    'flow.apartments.none' => 'Per queste date e questi ospiti non ci sono appartamenti disponibili. Prova con altre date o contattaci.',
    'flow.stay_line' => 'Dal {in} al {out} ({nights}) · {guests}.',
    'flow.price_total' => 'Totale',
    'flow.price_note' => 'Il prezzo è calcolato dal sistema ed è indicativo finché la richiesta non viene confermata dal gestore.',
    'flow.details.title' => 'I tuoi dati',
    'flow.summary.title' => 'Riepilogo e invio',
    'flow.not_a_booking' => 'Questa è una richiesta di disponibilità, non una prenotazione: il soggiorno è confermato solo dopo la risposta del gestore.',
    'flow.received.title' => 'Richiesta ricevuta',
    'flow.received.lead' => 'Abbiamo ricevuto la tua richiesta di disponibilità.',
    'flow.received.reference' => 'Riferimento della richiesta',
    'flow.received.next' => 'Ti risponderemo il prima possibile all’indirizzo email che ci hai indicato.',
    'flow.error.title' => 'Non è stato possibile inviare la richiesta',
    'flow.error.too_many' => 'Hai inviato troppe richieste in poco tempo. Riprova più tardi o contattaci.',
    'flow.error.conflict' => 'Nel frattempo queste date non sono più disponibili per l’appartamento scelto. Prova con altre date.',
    'flow.error.busy' => 'Il sistema è occupato: riprova tra qualche istante.',
    'flow.error.unavailable' => 'L’appartamento scelto non può ricevere questa richiesta online. Contattaci direttamente.',
    'flow.error.expired' => 'Il modulo è scaduto: controlla i dati e invialo di nuovo.',
    'flow.error.too_fast' => 'Il modulo è stato inviato troppo in fretta: controlla i dati e riprova.',
    'summary.apartment' => 'Appartamento',
    'summary.dates' => 'Date',
    'summary.contact' => 'Contatti',
    'summary.price' => 'Prezzo',
    'summary.total' => 'Totale',
    'summary.unquoted' => 'il gestore ti indicherà il prezzo nella risposta.',

    // Campi e pulsanti dei moduli
    'form.check_in' => 'Arrivo',
    'form.check_out' => 'Partenza',
    'form.guests' => 'Ospiti',
    'form.adults' => 'Adulti',
    'form.children' => 'Bambini',
    'form.pets' => 'Animali',
    'form.first_name' => 'Nome',
    'form.last_name' => 'Cognome',
    'form.email' => 'Email',
    'form.phone' => 'Telefono',
    'form.notes' => 'Note (facoltative)',
    'form.required_all' => 'Tutti i campi sono obbligatori.',
    'form.required_except_notes' => 'Tutti i campi sono obbligatori, tranne le note.',
    'form.honeypot' => 'Lascia vuoto questo campo',
    'form.privacy_before' => 'Ho letto l’',
    'form.privacy_link' => 'informativa sulla privacy',
    'form.privacy_after' => 'e acconsento al trattamento dei miei dati per rispondere alla richiesta.',
    'form.search' => 'Cerca appartamenti',
    'form.choose' => 'Scegli {name}',
    'form.continue' => 'Continua',
    'form.send' => 'Invia la richiesta',
    'form.back' => 'Indietro',
    'form.change_search' => 'Cambia date o ospiti',
    'form.edit_data' => 'Modifica i miei dati',

    // Unità
    'unit.night' => '{n} notte',
    'unit.nights' => '{n} notti',
    'unit.adult' => '{n} adulto',
    'unit.adults' => '{n} adulti',
    'unit.child' => '{n} bambino',
    'unit.children' => '{n} bambini',
    'unit.pet' => '{n} animale',
    'unit.pets' => '{n} animali',

    // Errori di validazione
    'err.generic' => 'Controlla questo campo.',
    'err.invalid_date' => 'Inserisci una data valida.',
    'err.check_out_not_after_check_in' => 'La partenza deve essere dopo l’arrivo.',
    'err.stay_too_long' => 'Il soggiorno è troppo lungo per una richiesta online: contattaci.',
    'err.check_in_in_past' => 'La data di arrivo non può essere passata.',
    'err.check_in_too_far' => 'La data di arrivo è troppo lontana nel tempo.',
    'err.invalid_adults' => 'Indica almeno un adulto.',
    'err.invalid_children' => 'Indica un numero valido di bambini.',
    'err.invalid_pets' => 'Indica un numero valido di animali.',
    'err.invalid_first_name' => 'Inserisci il nome.',
    'err.invalid_last_name' => 'Inserisci il cognome.',
    'err.invalid_email' => 'Inserisci un indirizzo email valido.',
    'err.invalid_phone' => 'Inserisci un numero di telefono valido.',
    'err.notes_too_long' => 'Le note sono troppo lunghe.',
    'err.invalid_locale' => 'Lingua non valida.',
    'err.privacy_required' => 'Per inviare la richiesta devi accettare l’informativa sulla privacy.',
    'err.invalid_apartment' => 'Scegli un appartamento.',
    'err.over_capacity' => 'Il numero di ospiti supera la capienza dell’appartamento.',
    'err.too_many_children' => 'Per questo appartamento i bambini possono essere al massimo {max}.',
    'err.pets_not_allowed' => 'In questo appartamento gli animali non sono ammessi.',
    'err.too_many_pets' => 'Per questo appartamento gli animali possono essere al massimo {max}.',
    'err.below_minimum_stay' => 'Per queste date il soggiorno minimo è di {min} notti.',
];
